### ISSUE TITLE
Is the release name semantic versioning/consistent for helm charts? 

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/helm-charts#13]
## Problem to be solved

`charon-0.1.0` is not a semantic versioning release name I'm familiar with, is this the standard release convention for helm charts? I'm not sure it is. 

## Proposed solution

Opt for a release naming convention that works well for helm and is aligned as much as possible with other ways we version our repos.

**Comment by eth2devops** [comment]
I doubled checked it, and it is the standard helm-release way when the repo has multiple charts then we can have a different release cycle for each chart. Helm promotes this approach through their helm-releaser github action. I lean towards this versioning over using a single version for all charts in the repo.
